version: "3.8"


volumes :
  mariadb :
    driver: local
    driver_opts:
      device: /tmp/dali3/db
      type: none
      o: bind
  wordpress :
    driver: local
    driver_opts:
      device: /tmp/dali3/wp
      type: none
      o: bind


services:
  mariadb:
    build : ./requirements/mariadb
    volumes :
      - mariadb:/var/lib/mysql
    env_file:
      ./.env
    networks:
      - network

  nginx:
    build: ./requirements/ngnix
    networks:
      - network
    ports:
      - "443:443"
    restart : always
    volumes : 
      - wordpress:/var/www/html
    depends_on:
      - wordpress

  wordpress :
    build : ./requirements/wordpress
    env_file:
      ./.env
    restart : always
    volumes : 
      - wordpress:/var/www/html/
    networks:
      - network
    depends_on:
      - mariadb

networks:
    network:
        driver: bridge

